"""empty message

Revision ID: 1b68633c3e0e
Revises: 772c1e4681b3
Create Date: 2020-05-25 11:39:35.557353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b68633c3e0e'
down_revision = '772c1e4681b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurement', sa.Column('submitted', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('measurement', 'submitted')
    # ### end Alembic commands ###
