"""empty message

Revision ID: 21f8bd54b83c
Revises: cf263ce6db62
Create Date: 2020-05-14 19:48:08.700495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21f8bd54b83c'
down_revision = 'cf263ce6db62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhook_subscription', sa.Column('secret', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webhook_subscription', 'secret')
    # ### end Alembic commands ###
