"""empty message

Revision ID: 229255540a0d
Revises: 2ccb22f388c5
Create Date: 2020-07-07 13:09:19.998272

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '229255540a0d'
down_revision = '2ccb22f388c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ggo', sa.Column('emissions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ggo', 'emissions')
    # ### end Alembic commands ###
