"""empty message

Revision ID: 2ccb22f388c5
Revises: af437055b9cd
Create Date: 2020-07-05 15:37:13.695058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ccb22f388c5'
down_revision = 'af437055b9cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_disclosure_ggo_settlement_id'), 'disclosure_ggo', ['settlement_id'], unique=False)
    op.drop_constraint('disclosure_ggo_settlement_id_fkey', 'disclosure_ggo', type_='foreignkey')
    op.create_foreign_key(None, 'disclosure_ggo', 'disclosure_settlement', ['settlement_id'], ['id'], ondelete='CASCADE')
    op.alter_column('disclosure_meteringpoint', 'disclosure_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('disclosure_meteringpoint_disclosure_id_fkey', 'disclosure_meteringpoint', type_='foreignkey')
    op.create_foreign_key(None, 'disclosure_meteringpoint', 'disclosure', ['disclosure_id'], ['id'], ondelete='CASCADE')
    op.alter_column('disclosure_settlement', 'disclosure_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('disclosure_settlement_disclosure_id_fkey', 'disclosure_settlement', type_='foreignkey')
    op.create_foreign_key(None, 'disclosure_settlement', 'disclosure', ['disclosure_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'disclosure_settlement', type_='foreignkey')
    op.create_foreign_key('disclosure_settlement_disclosure_id_fkey', 'disclosure_settlement', 'disclosure', ['disclosure_id'], ['id'])
    op.alter_column('disclosure_settlement', 'disclosure_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'disclosure_meteringpoint', type_='foreignkey')
    op.create_foreign_key('disclosure_meteringpoint_disclosure_id_fkey', 'disclosure_meteringpoint', 'disclosure', ['disclosure_id'], ['id'])
    op.alter_column('disclosure_meteringpoint', 'disclosure_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'disclosure_ggo', type_='foreignkey')
    op.create_foreign_key('disclosure_ggo_settlement_id_fkey', 'disclosure_ggo', 'disclosure_settlement', ['settlement_id'], ['id'])
    op.drop_index(op.f('ix_disclosure_ggo_settlement_id'), table_name='disclosure_ggo')
    # ### end Alembic commands ###
