"""empty message

Revision ID: 2f5db85cd250
Revises: 788103385109
Create Date: 2020-05-05 16:33:00.467769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f5db85cd250'
down_revision = '788103385109'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disclosure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('state', sa.Enum('PENDING', 'PROCESSING', 'AVAILABLE', name='disclosurestate'), nullable=False),
    sa.Column('sub', sa.String(), nullable=False),
    sa.Column('begin', sa.Date(), nullable=False),
    sa.Column('end', sa.Date(), nullable=False),
    sa.Column('publicize_meteringpoints', sa.Boolean(), nullable=False),
    sa.Column('publicize_gsrn', sa.Boolean(), nullable=False),
    sa.Column('publicize_physical_address', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index(op.f('ix_disclosure_id'), 'disclosure', ['id'], unique=False)
    op.create_index(op.f('ix_disclosure_public_id'), 'disclosure', ['public_id'], unique=False)
    op.create_index(op.f('ix_disclosure_sub'), 'disclosure', ['sub'], unique=False)
    op.create_table('disclosure_meteringpoint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disclosure_id', sa.Integer(), nullable=True),
    sa.Column('gsrn', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['disclosure_id'], ['disclosure.id'], ),
    sa.ForeignKeyConstraint(['gsrn'], ['meteringpoint.gsrn'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('disclosure_id', 'gsrn')
    )
    op.create_index(op.f('ix_disclosure_meteringpoint_disclosure_id'), 'disclosure_meteringpoint', ['disclosure_id'], unique=False)
    op.create_index(op.f('ix_disclosure_meteringpoint_id'), 'disclosure_meteringpoint', ['id'], unique=False)
    op.create_table('disclosure_settlement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disclosure_id', sa.Integer(), nullable=True),
    sa.Column('measurement_id', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['disclosure_id'], ['disclosure.id'], ),
    sa.ForeignKeyConstraint(['measurement_id'], ['measurement.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('disclosure_id', 'address'),
    sa.UniqueConstraint('disclosure_id', 'measurement_id')
    )
    op.create_index(op.f('ix_disclosure_settlement_disclosure_id'), 'disclosure_settlement', ['disclosure_id'], unique=False)
    op.create_index(op.f('ix_disclosure_settlement_id'), 'disclosure_settlement', ['id'], unique=False)
    op.create_index(op.f('ix_disclosure_settlement_measurement_id'), 'disclosure_settlement', ['measurement_id'], unique=False)
    op.create_table('disclosure_ggo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('settlement_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('begin', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sector', sa.String(), nullable=False),
    sa.Column('technology_code', sa.String(), nullable=False),
    sa.Column('fuel_code', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['settlement_id'], ['disclosure_settlement.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('settlement_id', 'address')
    )
    op.create_index(op.f('ix_disclosure_ggo_id'), 'disclosure_ggo', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_disclosure_ggo_id'), table_name='disclosure_ggo')
    op.drop_table('disclosure_ggo')
    op.drop_index(op.f('ix_disclosure_settlement_measurement_id'), table_name='disclosure_settlement')
    op.drop_index(op.f('ix_disclosure_settlement_id'), table_name='disclosure_settlement')
    op.drop_index(op.f('ix_disclosure_settlement_disclosure_id'), table_name='disclosure_settlement')
    op.drop_table('disclosure_settlement')
    op.drop_index(op.f('ix_disclosure_meteringpoint_id'), table_name='disclosure_meteringpoint')
    op.drop_index(op.f('ix_disclosure_meteringpoint_disclosure_id'), table_name='disclosure_meteringpoint')
    op.drop_table('disclosure_meteringpoint')
    op.drop_index(op.f('ix_disclosure_sub'), table_name='disclosure')
    op.drop_index(op.f('ix_disclosure_public_id'), table_name='disclosure')
    op.drop_index(op.f('ix_disclosure_id'), table_name='disclosure')
    op.drop_table('disclosure')
    # ### end Alembic commands ###
