"""empty message

Revision ID: 77a1bcbddf41
Revises: 2f5db85cd250
Create Date: 2020-05-06 13:16:10.987401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77a1bcbddf41'
down_revision = '2f5db85cd250'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disclosure', sa.Column('description', sa.String(), nullable=True))
    op.add_column('disclosure', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('disclosure', 'name')
    op.drop_column('disclosure', 'description')
    # ### end Alembic commands ###
