"""empty message

Revision ID: 8ac607623072
Revises: 1b68633c3e0e
Create Date: 2020-06-16 22:36:47.444458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ac607623072'
down_revision = '1b68633c3e0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("COMMIT")
    op.execute("ALTER TYPE event ADD VALUE 'ON_MEASUREMENT_PUBLISHED';")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("COMMIT")
    op.execute("ALTER TYPE event DROP VALUE 'ON_MEASUREMENT_PUBLISHED';")
    # ### end Alembic commands ###
