"""empty message

Revision ID: 96d3f5d67bcb
Revises: 9dfdca854a33
Create Date: 2020-06-30 17:45:13.230152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96d3f5d67bcb'
down_revision = '9dfdca854a33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE webhook_subscription SET url = REPLACE(url, 'on-ggos-issued', 'on-ggo-issued') WHERE url LIKE '%on-ggos-issued%';")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE webhook_subscription SET url = REPLACE(url, 'on-ggo-issued', 'on-ggos-issued') WHERE url LIKE '%on-ggo-issued%';")
    # ### end Alembic commands ###
