"""empty message

Revision ID: 9dfdca854a33
Revises: 8ac607623072
Create Date: 2020-06-18 09:22:29.638918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dfdca854a33'
down_revision = '8ac607623072'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        WITH existing AS (
          select * from webhook_subscription where url ilike 'http%://api.%'
        )
        INSERT INTO webhook_subscription (event, subject, secret, url)
        SELECT event, subject, secret, concat(substring(url from 0 for position('/webhook' in url)), '/webhook/on-measurement-published') FROM existing;
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM webhook_subscription where url ilike '%on-measurement-published%'")
    # ### end Alembic commands ###
