"""empty message

Revision ID: af437055b9cd
Revises: 96d3f5d67bcb
Create Date: 2020-07-02 16:07:51.600434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af437055b9cd'
down_revision = '96d3f5d67bcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("COMMIT;")
    op.execute("ALTER TYPE event ADD VALUE 'ON_METERINGPOINT_AVAILABLE';")
    op.execute("BEGIN;")
    op.execute("""
        UPDATE webhook_subscription
        SET event = 'ON_METERINGPOINT_AVAILABLE', url = REPLACE(url, 'on-meteringpoints-available', 'on-meteringpoint-available')
        WHERE event = 'ON_METERINGPOINTS_AVAILABLE';""")
    op.execute("COMMIT;")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        UPDATE webhook_subscription
        SET event = 'ON_METERINGPOINTS_AVAILABLE', url = REPLACE(url, 'on-meteringpoint-available', 'on-meteringpoints-available')
        WHERE event = 'ON_METERINGPOINT_AVAILABLE';""")
    op.execute("DELETE FROM pg_enum WHERE enumlabel = 'ON_METERINGPOINT_AVAILABLE';")
    # ### end Alembic commands ###
