"""empty message

Revision ID: cf263ce6db62
Revises: 77a1bcbddf41
Create Date: 2020-05-13 15:34:23.121260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf263ce6db62'
down_revision = '77a1bcbddf41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurement', sa.Column('published', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('measurement', 'published')
    # ### end Alembic commands ###
